name: Build and Push Docker Image

on:
  push:
    branches:  [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tb-services
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Image
        uses: docker/build-push-action@v6
        with: 
          context: ./trulyben
          file: ./trulyben/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tb-web:latest

      - name: Discord Notification
        if: success()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: Successful image tb-web:latest

      - name: Discord Failure Notification
        if: failure()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: Failed image tb-web:latest