name: Build and Push Docker Image

on:
  push:
    branches:  [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tb-services
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Image
        uses: docker/build-push-action@v6
        with: 
          context: ./host
          file: ./host/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tb-web:latest